name: Ruff
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------
      # Ruff Lint (errors & warnings)
      # -----------------------
      - name: Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          src: '.'
          args: 'check ./api ./lab-sdk .'
        continue-on-error: true

      # -----------------------
      # Ruff Format Check (shows what would be reformatted)
      # -----------------------
      - name: Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          src: '.'
          args: 'format --diff ./api ./lab-sdk .'
        continue-on-error: true
